#!/usr/bin/env Rscript

# The Germline Genomics of Cancer (G2C)
# Copyright (c) 2025-Present, Ryan L. Collins and the Dana-Farber Cancer Institute
# Contact: Ryan Collins <Ryan_Collins@dfci.harvard.edu>
# Distributed under the terms of the GNU GPL v2.0

# Impute genotypes for a single SV


#########
# Setup #
#########
# Load necessary libraries and constants
options(scipen=1000, stringsAsFactors=F)
require(argparse, quietly=TRUE)
require(G2CR, quietly=TRUE)


##################
# Data functions #
##################
# Load & normalize sample covariates
load.covars <- function(tsv.in, keep.samples=NULL){
  if(is.null(tsv.in)){
    return(NULL)
  }
  covars <- read.table(tsv.in, header=T, sep="\t", comment.char="")
  rownames(covars) <- covars[, 1]
  covars[, 1] <- NULL
  if(!is.null(keep.samples)){
    covars <- covars[intersect(rownames(covars), keep.samples), ]
  }
  for(i in 1:ncol(covars)){
    covars[, i] <- scale(as.numeric(covars[, i]))
  }
  impute.missing.values(covars)
}

# Determine the group of sample IDs that has the best balance of ref and nonref SV GTs
find.best.train.group <- function(sv.ad, groups.tsv){
  g.df <- read.table(groups.tsv, header=F, sep="\t")
  groups <- unique(g.df[, 2])
  g.k <- sapply(groups, function(gid){
    g.mems <- as.character(g.df[which(g.df[, 2] == gid), 1])
    min(table(sv.ad[intersect(names(sv.ad), g.mems)] > 0))
  })
  best.g <- head(names(g.k == max(g.k, na.rm=T)), 1)
  as.character(g.df[which(g.df[, 2] == best.g), 1])
}

# Train an SV genotype imputation model
train.imputation <- function(sv.ad, snp.ad, train.sids, covars=NULL){
  # Subset input data to training sids
  train.sv.ad <- sv.ad[intersect(train.sids, names(sv.ad))]
  train.snp.ad <- snp.ad[intersect(train.sids, rownames(snp.ad)), ]

  # Adjust training SV ADs for technical factors, if optioned
  if(!is.null(covars)){
    train.covars <- covars[intersect(train.sids, rownames(covars)), ]
    # TODO: implement this
  }

  # Fit imputation model
  # TODO: implement this
}


###########
# RScript #
###########
# Parse command line arguments and opions
parser <- ArgumentParser(description="Impute GTs for a single SV")
parser$add_argument("--ad", metavar=".tsv", type="character", required=TRUE,
                    help="Allele dosage matrix generated by extract_ad_matrix.py")
parser$add_argument("--sv-id", metavar="string", type="character", required=TRUE,
                    help="Variant ID for the SV to be imputed")
parser$add_argument("--sample-covariates", metavar=".tsv", type="character",
                    help="Optional .tsv of sample covariates for training")
parser$add_argument("--sample-group-labels", metavar=".tsv", type="character",
                    help=paste("Two-column .tsv mapping sample IDs to major",
                               "group labels, like ancestry. Will only be used ",
                               "for covariate adjustment during model training."))
args <- parser$parse_args()

# DEV:
args <- list("ad" = "~/Downloads/dfci-g2c.v1.chr19.final_cleanup_DEL_chr19_4680.ad.tsv.gz",
             "sv_id" = "dfci-g2c.v1.chr19.final_cleanup_DEL_chr19_4680",
             "sample_covariates" = "~/Downloads/dfci-g2c.v1.sv_imputation_covariates.tsv.gz",
             "sample_group_labels" = "~/scratch/dfci-g2c.v1.qc_ancestry.tsv")

# Load allele dosage matrix and split SV from SNPs
ad <- read.table(args$ad, header=T, sep="\t", comment.char="", check.names=F)
rownames(ad) <- ad$sample
ad$sample <- NULL
sv.ad <- ad[, args$sv_id]
names(sv.ad) <- rownames(ad)
snp.ad <- as.data.frame(ad[, setdiff(colnames(ad), args$sv_id)])
rownames(snp.ad) <- rownames(ad)
snp.ad <- impute.missing.values(snp.ad)

# If provided, load sample covariates
sv.samples <- names(sv.ad)[which(!is.na(sv.ad))]
covars <- load.covars(args$sample_covariates, keep.samples=sv.samples)

# Define training samples
train.sids <-if(!is.null(covars)){rownames(covars)}else{sv.samples}
train.sids <- intersect(train.sids,
                        find.best.train.group(sv.ad[train.sids], args$sample_group_labels))

# Train imputation model
sv.fit <- train.imputation(sv.ad, snp.ad, train.sids, covars)

# Apply trained model
# TODO: implement this

# SV imputation dev code

require(vioplot)
sv.pred <- predict(lm(`dfci-g2c.v1.chr19.final_cleanup_DEL_chr19_4680` ~ ., data=ad), newdata=ad)
sv.pred <- sv.pred * (2 / max(sv.pred, na.rm=T))
par(mfrow=c(1, 3))
vioplot(ad$chr19_2686315_G_A ~ ad$`dfci-g2c.v1.chr19.final_cleanup_DEL_chr19_4680`, main="Raw SV GTs", ylim=c(0, 2))
vioplot(sv.pred ~ ad$`dfci-g2c.v1.chr19.final_cleanup_DEL_chr19_4680`, main="Imputed SV GTs", ylim=c(0, 2))
vioplot(sv.pred ~ ad$`dfci-g2c.v1.chr19.final_cleanup_DEL_chr19_4680`, main="Raw vs. Imputed SV GTs", ylim=c(0, 2))


m <- merge(ad, covars, by="row.names", all=F, sort=F)
rownames(m) <- m$Row.names
m$Row.names <- NULL
m <- m[, grep("^chr19_", colnames(m), invert=T)]
adj.fit <- lm(`dfci-g2c.v1.chr19.final_cleanup_DEL_chr19_4680` ~ ., data=m)
adj <- predict(adj.fit, newdata=m)-summary(adj.fit)$coefficients["(Intercept)", "Estimate"]
sv.ad <- m$`dfci-g2c.v1.chr19.final_cleanup_DEL_chr19_4680` - adj

adj.sv.pred <- predict(lm(sv.ad ~ ., data=ad[names(sv.ad), setdiff(colnames(ad), "dfci-g2c.v1.chr19.final_cleanup_DEL_chr19_4680")]), newdata=ad)
adj.sv.pred <- adj.sv.pred * (2 / max(adj.sv.pred, na.rm=T))

par(mfrow=c(1, 2))
hist(sv.pred, breaks=100)
hist(adj.sv.pred, breaks=100)
