#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# The Germline Genomics of Cancer (G2C)
# Copyright (c) 2025-Present, Ryan L. Collins and the Dana-Farber Cancer Institute
# Contact: Ryan Collins <Ryan_Collins@dfci.harvard.edu>
# Distributed under the terms of the GNU GPL v2.0

"""
Refines GATK-SV genotypes with precomputed imputed GTs
"""


import argparse
import csv
import gzip
import pysam
import re
from g2cpy import convert_gt, determine_filetype
from sys import stdout


def load_update_gts(tsv_in):
    """
    Loads a .tsv of results generated by impute_sv_gts.R
    Returns a nested dict keyed by variant then by sample
    """

    updates = dict()

    if 'compressed' in determine_filetype(tsv_in):
        fin = gzip.open(tsv_in, 'rt')
    else:
        fin = open(tsv_in)

    for svid, sid, gt, gq, ad in csv.reader(fin, delimiter='\t'):
        if svid.startswith('#'):
            continue
        if svid not in updates.keys():
            updates[svid] = dict()
        updates[svid][sid] = {'GT' : gt, 'GQ' : int(gq), 
                              'AD' : round(float(ad), 2)}

    return updates


def update_gts(record, updates, gq_offset=0, compare=False):
    """
    Applies genotype updates to a single record
    N.b.: the `updates` dict here is an inner dict generated by load_update_gts()
    """

    total_n_samples = len(record.samples)
    n_updated = 0

    for sid, newvals in updates.items():
        if sid not in record.samples.keys():
            continue

        # Always add imputed allele depth and imputed GQ
        iq = newvals.get('GQ')
        record.samples[sid]['IAD'] = newvals.get('AD')
        record.samples[sid]['IQ'] = iq
        if iq is None:
            continue

        # Only update discordant GTs if new GQ exceeds original GQ
        # unless --no-compare was specified at runtime
        igt = convert_gt(newvals.get('GT', './.'))
        ogt = record.samples[sid].get('GT', (None, None,))
        if compare:
            if igt == ogt:
                continue
            ogq = record.samples[sid].get('GQ')
            if ogq is None:
                ogq = 0
            if iq <= ogq + gq_offset:
                continue

        # Otherwise, update GT
        record.samples[sid]['IMP'] = 1
        record.samples[sid]['OGT'] = convert_gt(ogt)
        record.samples[sid]['GT'] = igt
        n_updated += 1

    # If any genotypes were updated, add FRAC_IMPUTED to INFO
    if n_updated > 0 and total_n_samples > 0:
        record.info['FRAC_IMPUTED'] = n_updated / total_n_samples

    return record


def main():
    """
    Main block
    """
    parser = argparse.ArgumentParser(
             description=__doc__,
             formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('-i', '--input-vcf', required=True, metavar='VCF', 
                        help='Input .vcf. Required.')
    parser.add_argument('-u', '--update-tsv', required=True, metavar='.tsv',
                        help='Imputed genotype .tsv from impute_sv_gts.R. Required')
    parser.add_argument('--gq-offset', default=0, metavar='integer', type=int,
                        help='Difference between updated GQ and original GQ ' +
                        'before overwriting original GT. [default: 0]')
    parser.add_argument('--no-compare', default=False, action='store_true',
                        help='Always overwrite old genotypes without comparison')
    parser.add_argument('-o', '--output-vcf', metavar='VCF', default='stdout',
                        help='Output .vcf. [default: stdout]')
    args = parser.parse_args()

    # Open connection to input VCF
    invcf = pysam.VariantFile(args.input_vcf)

    # Update header for output VCF
    header = invcf.header
    if 'FRAC_IMPUTED' not in header.info.keys():
        header.add_line('##INFO=<ID=FRAC_IMPUTED,Number=1,Type=Float,Description="' +
                        'Fraction of sample genotypes overwritten by imputation.">')
    new_formats = {'OGT' : 'Number=1,Type=String,Description="Original ' +
                           'genotype prior to imputation">',
                   'IQ' : 'Number=1,Type=Float,Description="Imputation quality; ' +
                          'scaled the same as GATK GQ.">',
                   'IAD' : 'Number=1,Type=Float,Description="Imputed allele dosage">',
                   'IMP' : 'Number=1,Type=Integer,Description="Binary indicator ' +
                           'whether GT was imputed">'}
    for key, bline in new_formats.items():
        if key not in header.formats.keys():
            fline = ','.join(['##FORMAT=<ID={}', bline])
            header.add_line(fline.format(key))

    # Load dictionary of genotypes to update
    updates = load_update_gts(args.update_tsv)

    # Open connection to output VCF
    if args.output_vcf in 'stdout /dev/stdout -'.split():
        ovp = stdout
    else:
        ovp = args.output_vcf
    outvcf = pysam.VariantFile(ovp, 'w', header=header)

    # Iterate over records in input VCF
    for record in invcf:
        # Check if record has any genotypes to update
        if record.id in updates.keys():
            record = update_gts(record, updates[record.id], 
                                compare=not args.no_compare)

        # Write record to output VCF
        outvcf.write(record)

    # Clear buffer
    outvcf.close()


if __name__ == '__main__':
    main()

