#!/usr/bin/env bash

# The Germline Genomics of Cancer (G2C)
# Copyright (c) 2023-Present, Ryan L. Collins and the Dana-Farber Cancer Institute
# Contact: Ryan Collins <Ryan_Collins@dfci.harvard.edu>
# Distributed under the terms of the GNU GPL v2.0

# General helper bash functions for the All of Us Researcher Workbench v2.0 (Verily Pre)


# Legacy function (RW v1.0); unsure if this needs to be updated for Verily Pre
# # Update a contig-specific overrides .json for manage_chromshards.py with
# # arrays of VCFs and VCF indexes staged in a google bucket
# add_contig_vcfs_to_chromshard_overrides_json() {
#   # Check inputs
#   if [ $# -lt 4 ]; then
#     cat << EOF
# Error. Must provide at least four positional arguments:
#   1. path to overrides.json to be updated (or will be created if it doesn't exist)
#   2. base URI to search for .json mapping VCF arrays. Structure of this URI
#      is expected to follow the output from manage_chromshards.py; do not use 
#      this function if you have a custom URI directory structure.
#   3. VCF array key in .json
#   4. VCF index array key in .json
#   5. (Optional) path to contig list; defaults to workspace-specific contig list
# EOF
#     return 2
#   else
#     in_json=$1
#     base_uri=$( echo $2 | sed 's/\/$//g' )
#     vcf_key=$3
#     idx_key=$4
#   fi
#   if [ $# -ge 5 ]; then
#     contig_list=$5
#   else
#     contig_list=/home/jupyter/contig_lists/dfci-g2c.v1.contigs.$WN.list
#   fi

#   # Make temporary directory for staging
#   WRKDIR=`mktemp -d`

#   # Create overrides.json if it doesn't already exist; otherwise, make a copy for updating
#   if ! [ -e $in_json ]; then
#     echo "{}" > $WRKDIR/updates.json
#   else
#     cp $in_json $WRKDIR/updates.json
#   fi

#   # Add each chromosome's overrides
#   while read contig; do

#     # Attempt to locate this chromosome's .json map of outputs
#     gsutil ls $base_uri/$contig/*json > $WRKDIR/$contig.fmap.json.list
#     if [ $( cat $WRKDIR/$contig.fmap.json.list | wc -l ) -lt 1 ]; then
#       echo "Error: no .json was found for $contig in $base_uri/$contig/"
#       rm -rf $WRKDIR && unset WRKDIR
#       exit 2
#     elif [ $( cat $WRKDIR/$contig.fmap.json.list | wc -l ) -gt 1 ]; then
#       echo "Error: multiple .jsons were found for $contig in $base_uri/$contig/"
#       rm -rf $WRKDIR && unset WRKDIR
#       exit 2
#     else
#       contig_json=$( head -n1 $WRKDIR/$contig.fmap.json.list )
#     fi

#     # Write .json snippet for variable overrides for this contig
#     idx_uris=$( gsutil cat $contig_json | jq --arg k "$idx_key" '.[$k]' )
#     cat << EOF > $WRKDIR/$contig.overrides.json
# {
#   "$contig" : {
#       "CONTIG_VCFS": $( gsutil cat $contig_json | jq --arg key "$vcf_key" '[.[$key]] | flatten' ),
#       "CONTIG_VCF_IDXS": $( gsutil cat $contig_json | jq --arg key "$idx_key" '[.[$key]] | flatten' )
#     }
# }
# EOF
  
#     # Update main .json
#     code/scripts/update_json.py \
#       -i $WRKDIR/updates.json \
#       -u $WRKDIR/$contig.overrides.json \
#       -o $WRKDIR/updates.json
#   done < $contig_list

#   # Once updates are all complete, copy updated .json back to desired location
#   mv $WRKDIR/updates.json $in_json

#   # Clean up
#   rm -rf $WRKDIR
#   unset WRKDIR
# }


# Legacy function (RW v1.0); unsure if this needs to be updated for Verily Pre
# # Find all Cromwell return code files with non-zero exit status within a given bucket prefix
# # This is sometimes a useful alternative when cromshell continues to timeout
# # due to a Cromwell server being overloaded
# check_cromwell_return_codes() {
#    # Check inputs
#   if [ $# -ne 1 ]; then
#     echo "Must pass a gs:// bucket prefix as only input"
#     return
#   fi
#   bucket_prefix=$( echo $1 | sed 's/\/$//g' )
#   while read uri; do
#     rc=$( gsutil cat $uri )
#     if [ $rc != "0" ]; then
#       echo -e "$rc\t$uri"
#     fi
#   done < <( gsutil -m ls $bucket_prefix/**rc 2>/dev/null \
#             | fgrep -v memory_retry_rc | fgrep -v cacheCopy )
#   echo -e "Finished checking all return codes"
# }


# Clean up intermediate files generated by Cromwell and collected by check_status
cleanup_garbage() {
  dt_fmt=$( TZ=America/New_York date '+%m_%d_%Y.%Hh%Mm%Ss' )
  garbage_uri="$WORKSPACE_BUCKET/dumpster/dfci_g2c.aou_rw.$dt_fmt.garbage"
  if [ -e ~/uris_to_delete.list ]; then
    gsutil -m cp ~/uris_to_delete.list $garbage_uri
    rm ~/uris_to_delete.list
    cat << EOF | sed -e 's/\ //g' | paste -s -d\ > ~/cromshell/inputs/empty_dumpster.$dt_fmt.inputs.json
{
  "DeleteGcpObjects.uri_list" : "$garbage_uri",
  "DeleteGcpObjects.n_cpu" : 2,
  "DeleteGcpObjects.uris_per_shard" : 100000
}
EOF
    cromshell --no_turtle -t 120 -mc submit --no-validation \
      --options-json ~/code/refs/json/aou.cromwell_options.default.json \
      ~/code/wdl/pancan_germline_wgs/DeleteGcpObjects.wdl \
      ~/cromshell/inputs/empty_dumpster.$dt_fmt.inputs.json \
    | jq .id | tr -d '"' \
    >> ~/cromshell/job_ids/empty_dumpster.job_ids.list
  fi
}


# Concatenate a single-column text file into a Cromwell-parseable list of quoted strings
collapse_txt() {
   # Check inputs
  if [ $# -ne 1 ]; then
    echo "Must pass a single text file as input"
    return
  fi
  echo "["
  awk -v ORS='",' '{ print "\""$1 }' $1 | sed 's/,$//g' | sed 's/,/,\n/g'
  echo "]"
}


# Collect a table of peak task resource usage for an entire Cromwell workflow
gather_resource_usage() {
   # Check inputs
  if [ $# -ne 1 ]; then
    echo "Must pass a single workflow ID as input"
    return
  fi
  ~/code/scripts/summarize_workflow_resources.sh $wid
}


# Get G2C workspace processing number from within an AoU RW terminal
get_workspace_number() {
  if [[ -z $WORKSPACE_BUCKET ]]; then
    export WORKSPACE_BUCKET="gs://$( find ~/workspace -maxdepth 1 -name "rw-migration*" | head -n1 | xargs basename )"
  fi
  case "$WORKSPACE_BUCKET" in
    "gs://cloned-mybucket-wb-crisp-lemon-8858"|"gs://rw-migration-aou-rw-84a0039b")
      echo "w1"
      ;;
    "gs://cloned-mybucket-wb-brilliant-olive-6466"|"gs://rw-migration-aou-rw-78e2871d")
      echo "w2"
      ;;
    "gs://cloned-mybucket-wb-frigid-gourd-473"|"gs://rw-migration-aou-rw-3c78b3b7")
      echo "w3"
      ;;
    "gs://cloned-mybucket-wb-blissful-parsnip-2015"|"gs://rw-migration-aou-rw-efb2fd38")
      echo "w4"
      ;;
    "gs://cloned-mybucket-wb-spotless-pepper-8865"|"gs://rw-migration-aou-rw-484d2a66")
      echo "w5"
      ;;
    "gs://cloned-mybucket-wb-glossy-ruby-1828"|"gs://rw-migration-aou-rw-e34d8d8a")
      echo "dev"
      ;;
    *)
      echo "UNKNOWN"
      ;;
  esac
}


# Simple routine to monitor a single Cromwell workflow
# Required first positional argument is workflow ID
# Optional second positional argument is gate window (in minutes)
# Optional third positional argument is number of loops
monitor_workflow() {
  # Check inputs
  if [ $# -lt 1 ]; then
    echo "Must provide workflow ID as first positional argument"
    return 2
  fi
  if [ $# -ge 2 ]; then
    local monitor_gate=$2
  else
    local monitor_gate=5
  fi
  if [ $# -ge 3 ]; then
    local iter=$3
  else
    local iter=1000000
  fi

  # Print startup
  cat << EOF

+======================================+
|    DFCI G2C Workflow Monitor Loop    |
| $1 |
+======================================+
EOF

  # Endless loop
  local k=0
  while true; do
    ((k++))
    echo -e "\n"
    date
    njobs=$( gcloud compute instances list | wc -l )
    echo -e "Current Cromwell server load: $(( $njobs - 2 )) active VMs"
    ( cromshell -t 150 --no_turtle status $1 | jq .status ) 2>/dev/null 
    cromshell -t 150 --no_turtle counts -x $1 2>/dev/null
    if [ $k -ge $iter ]; then
      return 0
    fi
    echo -e "Waiting $monitor_gate minutes before checking again...\n"
    sleep ${monitor_gate}m
  done
}
